<a href="https://colab.research.google.com/github/pammehta2017/project/blob/master/Churnrate(v2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [26]:
df= pd.read_csv('Hiring_Challenge.csv')

In [27]:
#check the head of the data
df.head(10)

  C1     C2      C3 C4 C5  C6 C7     C8 C9 C10  C11 C12 C13  C14    C15  Hired
0  b  30.83   0.000  u  g   w  v  1.250  t   t    1   f   g  202      0      1
1  a  58.67   4.460  u  g   q  h  3.040  t   t    6   f   g   43    560      1
2  a   24.5   0.500  u  g   q  h  1.500  t   f    0   f   g  280    824      1
3  b  27.83   1.540  u  g   w  v  3.750  t   t    5   t   g  100      3      1
4  b  20.17   5.625  u  g   w  v  1.710  t   f    0   f   s  120      0      1
5  b  32.08   4.000  u  g   m  v  2.500  t   f    0   t   g  360      0      1
6  b  33.17   1.040  u  g   r  h  6.500  t   f    0   t   g  164  31285      1
7  a  22.92  11.585  u  g  cc  v  0.040  t   f    0   f   g   80   1349      1
8  b  54.42   0.500  y  p   k  h  3.960  t   f    0   f   g  180    314      1
9  b   42.5   4.915  y  p   w  v  3.165  t   f    0   t   g   52   1442      1

In [28]:
df.replace("?", np.NaN, inplace = True)

In [5]:
# check to see if there is any null or nan value
df.isnull().any().sum()

7

In [6]:
df.isnull().any().mean()

0.4375

In [29]:
df.columns

Index(['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11',
       'C12', 'C13', 'C14', 'C15', 'Hired'],
      dtype='object')

In [31]:
!pip install ppscore
import ppscore as pps

Requirement already satisfied: ppscore in /usr/local/lib/python3.6/dist-packages (1.2.0)
Requirement already satisfied: scikit-learn<1.0.0,>=0.20.2 in /usr/local/lib/python3.6/dist-packages (from ppscore) (0.22.2.post1)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from ppscore) (1.1.5)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.4.1)
Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.19.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.0.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.0.0->ppscore) (1.15.0)

In [32]:
pps.score(df,'C4', 'C5' )

{'baseline_score': 0.654700966881043,
 'case': 'classification',
 'is_valid_score': True,
 'metric': 'weighted F1',
 'model': DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                        max_depth=None, max_features=None, max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, presort='deprecated',
                        random_state=None, splitter='best'),
 'model_score': 1.0,
 'ppscore': 1.0,
 'x': 'C4',
 'y': 'C5'}

In [33]:
pps.score(df,'C5', 'C4' )

{'baseline_score': 0.654700966881043,
 'case': 'classification',
 'is_valid_score': True,
 'metric': 'weighted F1',
 'model': DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                        max_depth=None, max_features=None, max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, presort='deprecated',
                        random_state=None, splitter='best'),
 'model_score': 1.0,
 'ppscore': 1.0,
 'x': 'C5',
 'y': 'C4'}

In [34]:
pps.score(df,'C9', 'C10' )

{'baseline_score': 0.518840579710145,
 'case': 'classification',
 'is_valid_score': True,
 'metric': 'weighted F1',
 'model': DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                        max_depth=None, max_features=None, max_leaf_nodes=None,
                        min_impurity_decrease=0.0, min_impurity_split=None,
                        min_samples_leaf=1, min_samples_split=2,
                        min_weight_fraction_leaf=0.0, presort='deprecated',
                        random_state=None, splitter='best'),
 'model_score': 0.7113530437259289,
 'ppscore': 0.4001012053340088,
 'x': 'C9',
 'y': 'C10'}

In [35]:
mat = pps.matrix(df)

In [36]:
mat

         x  ...                                              model
0       C1  ...                                               None
1       C1  ...  DecisionTreeClassifier(ccp_alpha=0.0, class_we...
2       C1  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
3       C1  ...  DecisionTreeClassifier(ccp_alpha=0.0, class_we...
4       C1  ...  DecisionTreeClassifier(ccp_alpha=0.0, class_we...
..     ...  ...                                                ...
251  Hired  ...  DecisionTreeClassifier(ccp_alpha=0.0, class_we...
252  Hired  ...  DecisionTreeClassifier(ccp_alpha=0.0, class_we...
253  Hired  ...  DecisionTreeClassifier(ccp_alpha=0.0, class_we...
254  Hired  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
255  Hired  ...                                               None

[256 rows x 9 columns]

In [37]:
import seaborn as sns

In [38]:
df.drop('C5', axis=1, inplace= True)

In [39]:
df.columns

Index(['C1', 'C2', 'C3', 'C4', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12',
       'C13', 'C14', 'C15', 'Hired'],
      dtype='object')

In [18]:
sns.heatmap(mat, vmin=0, vmax=1, cmap='Blues', linewidths=0.5, annot=True)

ValueError: ignored

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      678 non-null    object
 1   C2      678 non-null    float64
 2   C3      690 non-null    float64
 3   C4      684 non-null    object
 4   C6      681 non-null    object
 5   C7      681 non-null    object
 6   C8      690 non-null    float64
 7   C9      690 non-null    object
 8   C10     690 non-null    object
 9   C11     690 non-null    int64
 10  C12     690 non-null    object
 11  C13     690 non-null    object
 12  C14     677 non-null    float64
 13  C15     690 non-null    int64
 14  Hired   690 non-null    int64
dtypes: float64(4), int64(3), object(8)
memory usage: 81.0+ KB

In [44]:
df['C2'] =pd.to_numeric(df['C2'], errors='coerce')
df['C14'] =pd.to_numeric(df['C14'], errors='coerce')

In [46]:
df.describe()

               C2          C3  ...            C15       Hired
count  678.000000  690.000000  ...     690.000000  690.000000
mean    31.568171    4.758725  ...    1017.385507    0.444928
std     11.957862    4.978163  ...    5210.102598    0.497318
min     13.750000    0.000000  ...       0.000000    0.000000
25%     22.602500    1.000000  ...       0.000000    0.000000
50%     28.460000    2.750000  ...       5.000000    0.000000
75%     38.230000    7.207500  ...     395.500000    1.000000
max     80.250000   28.000000  ...  100000.000000    1.000000

[8 rows x 7 columns]

In [47]:
# as there is pps score 1 for C4, C5 then we should remove 1 variable
df.head()

  C1     C2     C3 C4 C6 C7    C8 C9 C10  C11 C12 C13    C14  C15  Hired
0  b  30.83  0.000  u  w  v  1.25  t   t    1   f   g  202.0    0      1
1  a  58.67  4.460  u  q  h  3.04  t   t    6   f   g   43.0  560      1
2  a  24.50  0.500  u  q  h  1.50  t   f    0   f   g  280.0  824      1
3  b  27.83  1.540  u  w  v  3.75  t   t    5   t   g  100.0    3      1
4  b  20.17  5.625  u  w  v  1.71  t   f    0   f   s  120.0    0      1

In [48]:
df = pd.get_dummies(df)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 44 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C2      678 non-null    float64
 1   C3      690 non-null    float64
 2   C8      690 non-null    float64
 3   C11     690 non-null    int64
 4   C14     677 non-null    float64
 5   C15     690 non-null    int64
 6   Hired   690 non-null    int64
 7   C1_a    690 non-null    uint8
 8   C1_b    690 non-null    uint8
 9   C4_l    690 non-null    uint8
 10  C4_u    690 non-null    uint8
 11  C4_y    690 non-null    uint8
 12  C6_aa   690 non-null    uint8
 13  C6_c    690 non-null    uint8
 14  C6_cc   690 non-null    uint8
 15  C6_d    690 non-null    uint8
 16  C6_e    690 non-null    uint8
 17  C6_ff   690 non-null    uint8
 18  C6_i    690 non-null    uint8
 19  C6_j    690 non-null    uint8
 20  C6_k    690 non-null    uint8
 21  C6_m    690 non-null    uint8
 22  C6_q    690 non-null    uint8
 23  C6_r    690 non-null    uint8
 24  C6_w    690 non-null    uint8
 25  C6_x    690 non-null    uint8
 26  C7_bb   690 non-null    uint8
 27  C7_dd   690 non-null    uint8
 28  C7_ff   690 non-null    uint8
 29  C7_h    690 non-null    uint8
 30  C7_j    690 non-null    uint8
 31  C7_n    690 non-null    uint8
 32  C7_o    690 non-null    uint8
 33  C7_v    690 non-null    uint8
 34  C7_z    690 non-null    uint8
 35  C9_f    690 non-null    uint8
 36  C9_t    690 non-null    uint8
 37  C10_f   690 non-null    uint8
 38  C10_t   690 non-null    uint8
 39  C12_f   690 non-null    uint8
 40  C12_t   690 non-null    uint8
 41  C13_g   690 non-null    uint8
 42  C13_p   690 non-null    uint8
 43  C13_s   690 non-null    uint8
dtypes: float64(4), int64(3), uint8(37)
memory usage: 62.8 KB

In [49]:
df.corr()

             C2        C3        C8  ...     C13_g     C13_p     C13_s
C2     1.000000  0.202317  0.395751  ...  0.011673  0.013185 -0.017627
C3     0.202317  1.000000  0.298902  ...  0.123569 -0.037842 -0.116404
C8     0.395751  0.298902  1.000000  ...  0.031670 -0.065938 -0.007965
C11    0.185912  0.271207  0.322330  ...  0.142938 -0.053491 -0.130871
C14   -0.079812 -0.224242 -0.077163  ... -0.096916  0.031650  0.092257
C15    0.018553  0.123121  0.051345  ... -0.032303  0.238870 -0.058611
Hired  0.162881  0.206294  0.322475  ...  0.089056  0.039245 -0.109758
C1_a  -0.035886  0.041746 -0.086544  ...  0.083916 -0.012792 -0.084069
C1_b   0.036944 -0.028166  0.097009  ... -0.073421  0.016633  0.071440
C4_l  -0.062719  0.069678  0.044767  ... -0.167188  0.245988  0.081747
C4_u   0.099116  0.093017  0.082493  ...  0.044716 -0.157329  0.013731
C4_y  -0.099611 -0.083781 -0.075905  ...  0.039188 -0.060234 -0.018160
C6_aa -0.077886  0.023754 -0.059839  ...  0.057024 -0.031559 -0.048236
C6_c  -0.086075 -0.035728  0.015317  ...  0.023703 -0.019969 -0.017386
C6_cc -0.026983 -0.036943  0.060111  ...  0.039083 -0.027222 -0.030886
C6_d  -0.013843  0.001176  0.008507  ... -0.077217 -0.023091  0.090915
C6_e   0.143802  0.134457  0.108307  ...  0.009427 -0.021000 -0.001837
C6_ff  0.171520  0.062583 -0.077599  ...  0.037128  0.019599 -0.047018
C6_i   0.031526 -0.034094 -0.024744  ... -0.007843 -0.033118  0.021200
C6_j  -0.001456 -0.002236 -0.079577  ...  0.039108 -0.013134 -0.036390
C6_k  -0.004094 -0.042265 -0.058563  ... -0.022674 -0.030598  0.035957
C6_m   0.035220 -0.073015  0.025810  ... -0.204881 -0.026147  0.227567
C6_q  -0.063520  0.030992  0.045672  ...  0.083793 -0.038666 -0.073877
C6_r  -0.009977  0.011131  0.039224  ...  0.021311 -0.007157 -0.019830
C6_w  -0.048632 -0.012166 -0.008729  ...  0.034702 -0.034630 -0.023356
C6_x   0.009450  0.064218  0.062229  ...  0.056106 -0.026147 -0.049366
C7_bb  0.127234 -0.003667  0.074188  ... -0.043327 -0.033118  0.058853
C7_dd -0.064909  0.010693 -0.046331  ...  0.030204 -0.010144 -0.028105
C7_ff  0.169188  0.037302 -0.073321  ...  0.042705 -0.032500 -0.032676
C7_h   0.017316  0.061269  0.178414  ...  0.086824 -0.054153 -0.071071
C7_j  -0.012043 -0.033528 -0.062901  ... -0.011419 -0.011730  0.016678
C7_n  -0.054692 -0.002532 -0.009126  ...  0.024625 -0.008270 -0.022914
C7_o   0.005767  0.074880 -0.033147  ... -0.074900  0.245988 -0.016179
C7_v  -0.228667 -0.095540 -0.143370  ... -0.014196 -0.099407  0.053720
C7_z   0.242286  0.203351  0.194173  ...  0.034928 -0.011730 -0.032500
C9_f  -0.206151 -0.244317 -0.345689  ... -0.129207  0.113451  0.092985
C9_t   0.206151  0.244317  0.345689  ...  0.129207 -0.113451 -0.092985
C10_f -0.084307 -0.174846 -0.222982  ... -0.248609  0.093598  0.227403
C10_t  0.084307  0.174846  0.222982  ...  0.248609 -0.093598 -0.227403
C12_f -0.055282  0.013023 -0.138139  ... -0.007649  0.072382 -0.020030
C12_t  0.055282 -0.013023  0.138139  ...  0.007649 -0.072382  0.020030
C13_g  0.011673  0.123569  0.031670  ...  1.000000 -0.335843 -0.930505
C13_p  0.013185 -0.037842 -0.065938  ... -0.335843  1.000000 -0.032500
C13_s -0.017627 -0.116404 -0.007965  ... -0.930505 -0.032500  1.000000

[44 rows x 44 columns]

In [50]:
mat1 = pps.matrix(df)

In [54]:
mat1

          x  ...                                              model
0        C2  ...                                               None
1        C2  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
2        C2  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
3        C2  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
4        C2  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
...     ...  ...                                                ...
1931  C13_s  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
1932  C13_s  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
1933  C13_s  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
1934  C13_s  ...  DecisionTreeRegressor(ccp_alpha=0.0, criterion...
1935  C13_s  ...                                               None

[1936 rows x 9 columns]

In [53]:
sns.heatmap(mat1, vmin=0, vmax=1, cmap='Blues', linewidths=0.5, annot=True)

ValueError: ignored

In [55]:
df.dtypes

C2       float64
C3       float64
C8       float64
C11        int64
C14      float64
C15        int64
Hired      int64
C1_a       uint8
C1_b       uint8
C4_l       uint8
C4_u       uint8
C4_y       uint8
C6_aa      uint8
C6_c       uint8
C6_cc      uint8
C6_d       uint8
C6_e       uint8
C6_ff      uint8
C6_i       uint8
C6_j       uint8
C6_k       uint8
C6_m       uint8
C6_q       uint8
C6_r       uint8
C6_w       uint8
C6_x       uint8
C7_bb      uint8
C7_dd      uint8
C7_ff      uint8
C7_h       uint8
C7_j       uint8
C7_n       uint8
C7_o       uint8
C7_v       uint8
C7_z       uint8
C9_f       uint8
C9_t       uint8
C10_f      uint8
C10_t      uint8
C12_f      uint8
C12_t      uint8
C13_g      uint8
C13_p      uint8
C13_s      uint8
dtype: object

In [56]:
df.isnull().sum()

C2       12
C3        0
C8        0
C11       0
C14      13
C15       0
Hired     0
C1_a      0
C1_b      0
C4_l      0
C4_u      0
C4_y      0
C6_aa     0
C6_c      0
C6_cc     0
C6_d      0
C6_e      0
C6_ff     0
C6_i      0
C6_j      0
C6_k      0
C6_m      0
C6_q      0
C6_r      0
C6_w      0
C6_x      0
C7_bb     0
C7_dd     0
C7_ff     0
C7_h      0
C7_j      0
C7_n      0
C7_o      0
C7_v      0
C7_z      0
C9_f      0
C9_t      0
C10_f     0
C10_t     0
C12_f     0
C12_t     0
C13_g     0
C13_p     0
C13_s     0
dtype: int64

In [58]:
X = df.drop('Hired', axis= 1)
y = df['Hired']

In [59]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state = 0)

In [61]:
from sklearn.impute import KNNImputer

In [68]:
knn = KNNImputer(n_neighbors=5, add_indicator=True)

In [62]:
num = [col for col in X_train.columns if X_train[col].dtypes != 'O']

In [64]:
X_train[num].head()

        C2    C3      C8  C11    C14  ...  C12_f  C12_t  C13_g  C13_p  C13_s
127  22.75  11.0   2.500    7  100.0  ...      0      1      1      0      0
391  39.92   5.0   0.210    0  550.0  ...      1      0      1      0      0
21   23.25   1.0   0.835    0  300.0  ...      1      0      0      0      1
549  48.33  12.0  16.000    0  110.0  ...      1      0      0      0      1
339  28.00   3.0   0.750    0  300.0  ...      0      1      1      0      0

[5 rows x 43 columns]

In [70]:
knn.fit(X_train[num])

KNNImputer(add_indicator=True, copy=True, metric='nan_euclidean',
           missing_values=nan, n_neighbors=5, weights='uniform')

In [72]:
pd.DataFrame(knn.transform(X_train[num]))

        0       1       2    3      4       5   ...   39   40   41   42   43   44
0    22.75  11.000   2.500  7.0  100.0   809.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
1    39.92   5.000   0.210  0.0  550.0     0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0
2    23.25   1.000   0.835  0.0  300.0     0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0
3    48.33  12.000  16.000  0.0  110.0     0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0
4    28.00   3.000   0.750  0.0  300.0    67.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
..     ...     ...     ...  ...    ...     ...  ...  ...  ...  ...  ...  ...  ...
547  36.75   4.710   0.000  0.0  160.0     0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0
548  41.75   0.960   2.500  0.0  510.0   600.0  ...  0.0  1.0  0.0  0.0  0.0  0.0
549  19.58   0.665   1.665  0.0  220.0     5.0  ...  0.0  1.0  0.0  0.0  0.0  0.0
550  22.83   2.290   2.290  7.0  140.0  2384.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
551  40.58   3.290   3.500  0.0  400.0     0.0  ...  1.0  0.0  0.0  1.0  0.0  0.0

[552 rows x 45 columns]

In [73]:
pd.DataFrame(knn.transform(X_train[num])).isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
dtype: int64

In [74]:
X_test[num].isna().sum()

C2       0
C3       0
C8       0
C11      0
C14      3
C15      0
C1_a     0
C1_b     0
C4_l     0
C4_u     0
C4_y     0
C6_aa    0
C6_c     0
C6_cc    0
C6_d     0
C6_e     0
C6_ff    0
C6_i     0
C6_j     0
C6_k     0
C6_m     0
C6_q     0
C6_r     0
C6_w     0
C6_x     0
C7_bb    0
C7_dd    0
C7_ff    0
C7_h     0
C7_j     0
C7_n     0
C7_o     0
C7_v     0
C7_z     0
C9_f     0
C9_t     0
C10_f    0
C10_t    0
C12_f    0
C12_t    0
C13_g    0
C13_p    0
C13_s    0
dtype: int64

In [75]:
pd.DataFrame(knn.transform(X_test[num]))

        0       1       2     3      4       5   ...   39   40   41   42   43   44
0    45.83  10.500   5.000   7.0    0.0     0.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
1    64.08  20.000  17.500   9.0    0.0  1000.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
2    31.25   3.750   0.625   9.0  181.0     0.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
3    39.25   9.500   6.500  14.0  240.0  4607.0  ...  0.0  1.0  0.0  0.0  0.0  0.0
4    26.17   2.000   0.000   0.0  276.0     1.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
..     ...     ...     ...   ...    ...     ...  ...  ...  ...  ...  ...  ...  ...
133  28.58   3.625   0.250   0.0  100.0     0.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
134  26.50   2.710   0.085   0.0   80.0     0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0
135  52.42   1.500   3.750   0.0    0.0   350.0  ...  1.0  1.0  0.0  0.0  0.0  0.0
136  34.75   2.500   0.500   0.0  348.0     0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0
137  20.67   0.415   0.125   0.0    0.0    44.0  ...  0.0  1.0  0.0  0.0  0.0  0.0

[138 rows x 45 columns]

In [76]:
pd.DataFrame(knn.transform(X_test[num])).isna().sum().sum()

0

In [ ]:
model_eval = pd.DataFrame(index= ['Random Forest'], columns =['Score'])

In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
ypred = rf.predict(X_test)

In [ ]:
log = LogisticRegression()
log.fit(X_train, y_train)
ypred2 = log.predict(X_test)

In [ ]:
xg = XGBClassifier()
xg.fit(X_train, y_train)
ypred3 = xg.predict(X_test)

In [ ]:
model_eval.loc['Random Forest', 'Score'] = accuracy_score(ypred, y_test)
model_eval.loc['Logistic', 'Score'] = accuracy_score(ypred2, y_test)
model_eval.loc['XGBoost', 'Score'] = accuracy_score(ypred3, y_test)

In [ ]:
model_eval

                  Score
Random Forest  0.833333
Logistic        0.84058
XGBoost        0.833333

In [ ]:
import joblib
joblib.dump(log,'model')

['model']

In [ ]:
rf.feature_importances_

array([5.85893601e-02, 6.53136151e-02, 6.94971809e-02, 5.48170863e-02,
       6.45525502e-02, 5.80964360e-02, 8.47208145e-03, 8.00912928e-03,
       2.59217499e-03, 1.29934182e-02, 1.32528549e-02, 7.68342140e-03,
       7.58852941e-03, 6.27041048e-03, 3.47412323e-03, 2.66674355e-03,
       5.40223147e-03, 7.49799661e-03, 4.77520925e-04, 7.31960659e-03,
       2.45522414e-03, 8.02474657e-03, 9.48872805e-05, 8.76008313e-03,
       7.96204371e-03, 7.52214549e-03, 3.16916899e-04, 5.51632292e-03,
       1.10617383e-02, 7.29637568e-05, 2.58360999e-03, 3.30687021e-04,
       8.50876711e-03, 9.46949416e-04, 1.77313847e-01, 1.77425424e-01,
       4.51989555e-02, 3.34995760e-02, 7.35887840e-03, 9.30082508e-03,
       8.63264107e-03, 4.14615881e-03, 8.40013705e-03])

In [ ]:
weights = pd.DataFrame(rf.feature_importances_, index= X.columns.values)

In [ ]:
weights

              0
C2     0.058589
C3     0.065314
C8     0.069497
C11    0.054817
C14    0.064553
C15    0.058096
C1_a   0.008472
C1_b   0.008009
C4_l   0.002592
C4_u   0.012993
C4_y   0.013253
C6_aa  0.007683
C6_c   0.007589
C6_cc  0.006270
C6_d   0.003474
C6_e   0.002667
C6_ff  0.005402
C6_i   0.007498
C6_j   0.000478
C6_k   0.007320
C6_m   0.002455
C6_q   0.008025
C6_r   0.000095
C6_w   0.008760
C6_x   0.007962
C7_bb  0.007522
C7_dd  0.000317
C7_ff  0.005516
C7_h   0.011062
C7_j   0.000073
C7_n   0.002584
C7_o   0.000331
C7_v   0.008509
C7_z   0.000947
C9_f   0.177314
C9_t   0.177425
C10_f  0.045199
C10_t  0.033500
C12_f  0.007359
C12_t  0.009301
C13_g  0.008633
C13_p  0.004146
C13_s  0.008400